# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC Tenant Workflow

on:
  workflow_dispatch
  
env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  export:
    name: Export Azure Policy Compliance
    uses: ./.github/workflows/export-compliance.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: TENANT-PLAN
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit
