# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC Compliance Report

on:
  workflow_dispatch
  
env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan tenant
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: TENANT-PLAN
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit
